FROM ruby:3.2.2

RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs npm libvips postgresql-client

WORKDIR /app

COPY Gemfile Gemfile.lock /app/

RUN bundle install

COPY . /app

RUN npm i

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
